{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3930d4dd-25a1-444f-ae77-26c6b125d315",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-03-02 17:31:10.570 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\Localuser\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import json\n",
    "import yaml\n",
    "from typing import Optional, Dict, Any, List\n",
    "import matplotlib.pyplot as plt  # Import matplotlib\n",
    "import os\n",
    "\n",
    "# ----------------------- Constants -----------------------\n",
    "SUPPORTED_FILE_TYPES = [\"csv\", \"json\", \"yaml\", \"yml\"]\n",
    "DEFAULT_MODEL_NAME = \"your_model_name\"\n",
    "DEFAULT_VIEW_NAME = \"your_view_name\"\n",
    "DEFAULT_DASHBOARD_TITLE = \"My Advanced LookML Dashboard\"\n",
    "DEFAULT_TIMEZONE = \"America/Los_Angeles\"\n",
    "\n",
    "# ----------------------- Helper Functions -----------------------\n",
    "def to_lookml_name(name: str) -> str:\n",
    "    \"\"\"Converts a string to snake_case for LookML compatibility.\"\"\"\n",
    "    return name.lower().replace(\" \", \"_\")\n",
    "\n",
    "def infer_data_type(column: pd.Series) -> str:\n",
    "    \"\"\"Infers the data type of a Pandas Series.\"\"\"\n",
    "    if pd.api.types.is_datetime64_any_dtype(column):\n",
    "        return \"date\"\n",
    "    elif pd.api.types.is_numeric_dtype(column):\n",
    "        return \"number\"\n",
    "    else:\n",
    "        return \"string\"\n",
    "\n",
    "# ----------------------- Automated Classification -----------------------\n",
    "def auto_classify_columns(df: pd.DataFrame) -> Dict[str, Dict[str, str]]:\n",
    "    \"\"\"Automatically classifies columns as dimensions or measures.\"\"\"\n",
    "    column_config = {}\n",
    "\n",
    "    for col in df.columns:\n",
    "        unique_ratio = df[col].nunique() / len(df)\n",
    "        data_type = infer_data_type(df[col])\n",
    "\n",
    "        # Classify based on uniqueness and data type\n",
    "        if data_type == \"number\":\n",
    "            field_type = \"measure\" if unique_ratio < 0.1 else \"dimension\"\n",
    "        elif data_type == \"date\":\n",
    "            field_type = \"dimension\"\n",
    "        elif data_type == \"yesno\":\n",
    "            field_type = \"dimension\"\n",
    "        else:\n",
    "            field_type = \"dimension\" if unique_ratio > 0.1 else \"measure\"\n",
    "\n",
    "        column_config[col] = {\n",
    "            \"field_type\": field_type,\n",
    "            \"data_type\": data_type,\n",
    "        }\n",
    "\n",
    "    return column_config\n",
    "\n",
    "# ----------------------- Dashboard Suggestion -----------------------\n",
    "def suggest_dashboard_layout(df: pd.DataFrame) -> List[Dict[str, Any]]:\n",
    "    \"\"\"Suggests dashboard tiles based on dataset structure.\"\"\"\n",
    "    column_config = auto_classify_columns(df)\n",
    "    time_fields = [col for col, cfg in column_config.items() if cfg[\"data_type\"] == \"date\"]\n",
    "    numeric_measures = [col for col, cfg in column_config.items() if cfg[\"field_type\"] == \"measure\"]\n",
    "    categorical_dimensions = [col for col, cfg in column_config.items() if cfg[\"field_type\"] == \"dimension\"]\n",
    "\n",
    "    tile_suggestions = []\n",
    "\n",
    "    # 1️⃣ Trend over time (Line Chart)\n",
    "    if time_fields and numeric_measures:\n",
    "        for time_field in time_fields:\n",
    "            for measure in numeric_measures:\n",
    "                tile_suggestions.append({\n",
    "                    \"tile_title\": f\"{measure} Trend Over {time_field}\",\n",
    "                    \"tile_type\": \"looker_line\",\n",
    "                    \"selected_fields\": [time_field, measure],\n",
    "                    \"pivots\": [],\n",
    "                    \"filters\": [],\n",
    "                    \"description\": f\"Shows how {measure} changes over time, using {time_field} as the time axis.\"\n",
    "                })\n",
    "\n",
    "    # 2️⃣ Category-wise summary (Bar Chart)\n",
    "    if categorical_dimensions and numeric_measures:\n",
    "        for dimension in categorical_dimensions:\n",
    "            for measure in numeric_measures:\n",
    "                 tile_suggestions.append({\n",
    "                     \"tile_title\": f\"Top {dimension} by {measure}\",\n",
    "                     \"tile_type\": \"looker_bar\",\n",
    "                     \"selected_fields\": [dimension, measure],\n",
    "                     \"pivots\": [],\n",
    "                     \"filters\": [],\n",
    "                     \"description\": f\"Displays the top categories from {dimension} based on the values of {measure}.\"\n",
    "                 })\n",
    "\n",
    "    # 3️⃣ Summary KPI (Single Value)\n",
    "    if numeric_measures:\n",
    "        for measure in numeric_measures:\n",
    "            tile_suggestions.append({\n",
    "                \"tile_title\": f\"Total {measure}\",\n",
    "                \"tile_type\": \"single_value\",\n",
    "                \"selected_fields\": [measure],\n",
    "                \"pivots\": [],\n",
    "                \"filters\": [],\n",
    "                \"description\": f\"Shows the total value for {measure}.\"\n",
    "            })\n",
    "\n",
    "    return tile_suggestions\n",
    "\n",
    "# ----------------------- Dashboard Mockup -----------------------\n",
    "def generate_dashboard_mockup(tile_suggestions: List[Dict[str, Any]]):\n",
    "    \"\"\"Generates a simple visual representation of the suggested Looker dashboard layout.\"\"\"\n",
    "    if not tile_suggestions:\n",
    "        st.warning(\"No dashboard tiles suggested.\")\n",
    "        return\n",
    "\n",
    "    fig, ax = plt.subplots(len(tile_suggestions), 1, figsize=(8, len(tile_suggestions) * 2))\n",
    "\n",
    "    if len(tile_suggestions) == 1:\n",
    "        ax = [ax]  # Ensure it's iterable\n",
    "\n",
    "    for i, tile in enumerate(tile_suggestions):\n",
    "        ax[i].text(0.5, 0.5, tile[\"tile_title\"], fontsize=12, ha='center', va='center',\n",
    "                    bbox=dict(boxstyle=\"round\", edgecolor=\"black\", facecolor=\"lightgrey\"))\n",
    "        ax[i].set_xticks([])\n",
    "        ax[i].set_yticks([])\n",
    "        ax[i].set_frame_on(False)\n",
    "    plt.tight_layout()\n",
    "    st.pyplot(fig)  # Use st.pyplot to display the Matplotlib figure in Streamlit\n",
    "\n",
    "# ----------------------- File Loading -----------------------\n",
    "def load_flat_file(uploaded_file) -> Optional[pd.DataFrame]:\n",
    "    \"\"\"Loads a flat file (CSV, JSON, YAML) into a Pandas DataFrame.\"\"\"\n",
    "    try:\n",
    "        if uploaded_file.name.endswith(\".csv\"):\n",
    "            return pd.read_csv(uploaded_file)\n",
    "        elif uploaded_file.name.endswith(\".json\"):\n",
    "            raw_json = json.load(uploaded_file)\n",
    "            if isinstance(raw_json, list):\n",
    "                return pd.json_normalize(raw_json)\n",
    "            elif isinstance(raw_json, dict):\n",
    "                return pd.json_normalize(raw_json)\n",
    "            else:\n",
    "                st.error(\"⚠️ Unsupported JSON format: Must be a list or dictionary.\")\n",
    "                return None\n",
    "        elif uploaded_file.name.endswith((\".yaml\", \".yml\")):\n",
    "            try:\n",
    "                raw_yaml = yaml.safe_load(uploaded_file)\n",
    "            except yaml.YAMLError as e:\n",
    "                st.error(f\"⚠️ Error parsing YAML file: {e}\")\n",
    "                return None\n",
    "\n",
    "            if isinstance(raw_yaml, list):\n",
    "                return pd.json_normalize(raw_yaml)\n",
    "            elif isinstance(raw_yaml, dict):\n",
    "                return pd.json_normalize(raw_yaml)\n",
    "            else:\n",
    "                st.error(\"⚠️ Unsupported YAML format: Must be a list or dictionary.\")\n",
    "                return None\n",
    "        else:\n",
    "            st.error(f\"❌ Unsupported file format. Please upload one of: {', '.join(SUPPORTED_FILE_TYPES)}\")\n",
    "            return None\n",
    "    except Exception as e:\n",
    "        st.error(f\"⚠️ Error loading file: {e}\")\n",
    "        return None\n",
    "\n",
    "# ----------------------- LookML Generation -----------------------\n",
    "def generate_lookml_view(df: pd.DataFrame, view_name: str, column_config: Dict[str, Dict[str, str]],\n",
    "                         sql_table_name: str) -> str:\n",
    "    \"\"\"Generates a LookML view from a DataFrame and user-defined column configurations.\"\"\"\n",
    "\n",
    "    lookml_template = f\"view: {view_name} {{\\n\"\n",
    "    lookml_template += f\"  sql_table_name: {sql_table_name} ;;\\n\\n\"\n",
    "\n",
    "    for col, config in column_config.items():\n",
    "        col_lookml_name = to_lookml_name(col)\n",
    "        field_type = config[\"field_type\"]\n",
    "        data_type = config[\"data_type\"]\n",
    "\n",
    "        if field_type == \"dimension\":\n",
    "            if data_type in [\"date\", \"datetime\", \"timestamp\"]:\n",
    "                lookml_template += f\"  dimension_group: {col_lookml_name} {{\\n\"\n",
    "                lookml_template += \"    type: time\\n\"\n",
    "                lookml_template += \"    timeframes: [raw, date, week, month, quarter, year]\\n\"  # Added 'date'\n",
    "                lookml_template += f\"    sql: ${{TABLE}}.{col} ;;\\n\"\n",
    "                lookml_template += \"  }\\n\\n\"\n",
    "            else:\n",
    "                lookml_template += f\"  dimension: {col_lookml_name} {{\\n\"\n",
    "                lookml_template += f\"    type: {data_type}\\n\"\n",
    "                lookml_template += f\"    sql: ${{TABLE}}.{col} ;;\\n\"\n",
    "                lookml_template += \"  }\\n\\n\"\n",
    "\n",
    "        elif field_type == \"measure\":\n",
    "            lookml_template += f\"  measure: {col_lookml_name} {{\\n\"\n",
    "            lookml_template += f\"    type: sum\\n\"  # Default aggregation to sum\n",
    "            lookml_template += f\"    sql: ${{TABLE}}.{col} ;;\\n\"\n",
    "            lookml_template += \"  }\\n\\n\"\n",
    "\n",
    "    lookml_template += \"}\"\n",
    "    return lookml_template\n",
    "\n",
    "def generate_lookml_dashboard(dashboard_title: str, view_name: str, tile_configs: List[Dict[str, Any]]) -> str:\n",
    "    \"\"\"Generates a LookML dashboard from user-defined configurations.\"\"\"\n",
    "\n",
    "    dashboard_name = to_lookml_name(dashboard_title)\n",
    "    dashboard_template = {\n",
    "        'dashboard': dashboard_name,\n",
    "        'title': dashboard_title,\n",
    "        'layout': 'newspaper',\n",
    "        'preferred_viewer': 'dashboards-next',\n",
    "        'elements': []\n",
    "    }\n",
    "    for config in tile_configs:\n",
    "        element = {\n",
    "            'title': config['tile_title'],\n",
    "            'name': to_lookml_name(config['tile_title']),\n",
    "            'model': DEFAULT_MODEL_NAME,\n",
    "            'explore': view_name,\n",
    "            'type': config['tile_type'],\n",
    "            'fields': config['selected_fields'],\n",
    "            'pivots': config.get('pivots', []),\n",
    "            'fill_fields': config.get('fill_fields', config['selected_fields']),\n",
    "            'filters': config.get('filters', {}),\n",
    "            'sorts': config.get('sorts', []),\n",
    "            'limit': config.get('limit', 500),\n",
    "            'column_limit': config.get('column_limit', 50),\n",
    "            'query_timezone': DEFAULT_TIMEZONE,  # Use the constant\n",
    "            'row': config.get('row', 0),\n",
    "            'col': config.get('col', 0),\n",
    "            'width': config.get('width', 8),\n",
    "            'height': config.get('height', 6),\n",
    "            'show_view_names': config.get('show_view_names', False),\n",
    "            'show_y_axis_labels': config.get('show_y_axis_labels', True),\n",
    "            'show_x_axis_label': config.get('show_x_axis_label', True),\n",
    "            'y_axis_scale_mode': config.get('y_axis_scale_mode', 'linear'),\n",
    "            'x_axis_scale': config.get('x_axis_scale', 'auto'),\n",
    "            'legend_position': config.get('legend_position', 'center'),\n",
    "            'show_value_labels': config.get('show_value_labels', True),\n",
    "            'dynamic_fields': config.get('dynamic_fields', [])\n",
    "        }\n",
    "        dashboard_template['elements'].append(element)\n",
    "    return yaml.dump([dashboard_template], sort_keys=False, default_flow_style=False)\n",
    "\n",
    "# ----------------------- Streamlit App -----------------------\n",
    "def main():\n",
    "    st.title(\"🔍 AutoML dashboard\")\n",
    "\n",
    "    # File Upload Section\n",
    "    uploaded_file = st.file_uploader(\n",
    "        \"Upload CSV, JSON, or YAML file\", type=SUPPORTED_FILE_TYPES\n",
    "    )\n",
    "\n",
    "    if uploaded_file is not None:\n",
    "        data = load_flat_file(uploaded_file)\n",
    "\n",
    "        if data is not None:\n",
    "            st.write(\"### 🗂️ Data Preview\")\n",
    "            st.dataframe(data.head())\n",
    "\n",
    "            # View Configuration\n",
    "            st.write(\"### ⚙️ View Configuration\")\n",
    "            view_name = st.text_input(\"View Name\", value=DEFAULT_VIEW_NAME)\n",
    "            sql_table_name = st.text_input(\"SQL Table Name\", value=f\"ANALYTICS_DEV.GSUNDARESAN_CORE.{view_name}\")\n",
    "\n",
    "            # --- Automated Column Configuration ---\n",
    "            if st.checkbox(\"✨ Auto-Configure Columns\"):\n",
    "                column_config = auto_classify_columns(data)\n",
    "                st.write(\"#### Auto-Generated Column Configuration:\")\n",
    "                st.write(column_config)\n",
    "            else:\n",
    "                column_config = {}\n",
    "                st.write(\"### 🔧 Configure Columns:\")\n",
    "\n",
    "                for col in data.columns:\n",
    "                    st.markdown(f\"**Column:** `{col}`\")\n",
    "                    col_dtype = data[col].dtype\n",
    "                    default_field_type = \"dimension\"\n",
    "                    default_data_type = infer_data_type(data[col])\n",
    "\n",
    "                    field_type = st.selectbox(\n",
    "                        f\"Field type for `{col}`\",\n",
    "                        [\"dimension\", \"measure\", \"exclude\"],\n",
    "                        index=0 if default_field_type == \"dimension\" else 1,\n",
    "                        key=f\"field_{col}\",\n",
    "                    )\n",
    "\n",
    "                    if field_type == \"exclude\":\n",
    "                        continue\n",
    "\n",
    "                    data_type = st.selectbox(\n",
    "                        f\"Data type for `{col}`\",\n",
    "                        [\"string\", \"number\", \"date\", \"yesno\"],  # Added 'yesno'\n",
    "                        index=[\"string\", \"number\", \"date\", \"yesno\"].index(default_data_type),\n",
    "                        key=f\"data_{col}\",\n",
    "                    )\n",
    "\n",
    "                    column_config[col] = {\n",
    "                        \"field_type\": field_type,\n",
    "                        \"data_type\": data_type,\n",
    "                    }\n",
    "                    st.write(\"---\")\n",
    "\n",
    "            if st.button(\"🚀 Generate LookML View\"):\n",
    "                if not column_config:\n",
    "                    st.error(\"❌ Please configure at least one column as a dimension or measure.\")\n",
    "                else:\n",
    "                    lookml_content = generate_lookml_view(data, view_name, column_config, sql_table_name)\n",
    "                    st.success(\"✅ LookML View Generated Successfully!\")\n",
    "                    st.code(lookml_content, language=\"lookml\")  # Use 'lookml' for syntax highlighting\n",
    "\n",
    "                    st.download_button(\n",
    "                        label=\"📥 Download LookML View\",\n",
    "                        data=lookml_content,\n",
    "                        file_name=f\"{view_name}.view.lkml\",\n",
    "                        mime=\"text/plain\",  # Changed to 'text/plain'\n",
    "                    )\n",
    "\n",
    "            # Dashboard Section\n",
    "            st.write(\"### 🗂️ **Create Advanced LookML Dashboard**\")\n",
    "            dashboard_title = st.text_input(\"📊 Dashboard Title\", value=DEFAULT_DASHBOARD_TITLE)\n",
    "\n",
    "            # --- Automated Dashboard Suggestions ---\n",
    "            if st.checkbox(\"💡 Suggest Dashboard Layout\"):\n",
    "                tile_suggestions = suggest_dashboard_layout(data)\n",
    "                st.write(\"#### Suggested Dashboard Layout:\")\n",
    "                st.write(tile_suggestions)\n",
    "                st.write(\"#### Dashboard Mockup:\")\n",
    "                generate_dashboard_mockup(tile_suggestions)  # Display the mockup\n",
    "                # Use the suggested tiles as default\n",
    "                tile_configs = tile_suggestions\n",
    "            else:\n",
    "                tile_configs = []\n",
    "                num_tiles = st.number_input(\"🧱 Number of Tiles\", min_value=1, max_value=10, value=2, step=1)\n",
    "\n",
    "                for i in range(num_tiles):\n",
    "                    st.subheader(f\"Tile {i+1} Configuration\")\n",
    "                    tile_title = st.text_input(f\"Tile {i+1} Title\", value=f\"Tile {i+1}\", key=f\"tile_title_{i}\")\n",
    "                    model_name = st.text_input(f\"Model Name for Tile {i+1}\", value=DEFAULT_MODEL_NAME, key=f\"model_name_{i}\")\n",
    "                    tile_type = st.selectbox(f\"Tile Type for Tile {i+1}\",\n",
    "                                            [\"looker_line\", \"looker_bar\", \"single_value\", \"looker_grid\"],\n",
    "                                            key=f\"tile_type_{i}\")\n",
    "\n",
    "                    # Fetching time-based and non-time-based fields\n",
    "                    date_fields = [col for col in data.columns if\n",
    "                                'date' in col.lower() or pd.api.types.is_datetime64_any_dtype(data[col])]\n",
    "                    all_dimensions = list(data.columns) + [f\"{col}_year\" for col in date_fields] + [\n",
    "                                        f\"{col}_month\" for col in date_fields]\n",
    "\n",
    "                    selected_fields = st.multiselect(f\"Select Fields for Tile {i+1}\", all_dimensions, key=f\"fields_{i}\")\n",
    "\n",
    "                    # Pivots\n",
    "                    pivot_options = [None] + list(data.columns)\n",
    "\n",
    "                    tile_configs.append({\n",
    "                        \"tile_title\": tile_title,\n",
    "                        \"model_name\": model_name,\n",
    "                        \"tile_type\": tile_type,\n",
    "                        \"selected_fields\": selected_fields\n",
    "                    })\n",
    "\n",
    "            if st.button(\"✨ Generate LookML Dashboard\"):\n",
    "                if not tile_configs:\n",
    "                    st.error(\"❌ Please configure at least one tile for the dashboard.\")\n",
    "                else:\n",
    "                    lookml_dashboard_content = generate_lookml_dashboard(dashboard_title, view_name, tile_configs)\n",
    "                    st.success(\"✅ LookML Dashboard Generated Successfully!\")\n",
    "                    st.code(lookml_dashboard_content, language=\"yaml\")\n",
    "                    st.download_button(\n",
    "                        \"📥 Download LookML Dashboard\",\n",
    "                        data=lookml_dashboard_content,\n",
    "                        file_name=f\"{dashboard_title}.dashboard.lookml\",\n",
    "                        mime=\"text/plain\",\n",
    "                    )\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
